maze_solver_node:
  ros__parameters:
  
    use_sim_time: true
    base_link: "base_link"
    laser_link: "laser"

    num_waypoints: -1             # (-1 all) waypoints
    odom_topic: "/odometry/filtered"
    laser_topic: "/scan"

    # PID gain
    # Distance Controller
    DkP: 1.4
    DkI: 0.0001
    DkD: 0.8
    # Turn Controller
    TkP: 3.0
    TkI: 0.0001
    TkD: 2.8

    max_ang_vel: 1.5
    max_lin_vel: 3.0

    yaw_tolerance: 0.01         # rad
    goal_tolerance: 0.03

    # front_stop_thresh: 0.25
    front_stop_thresh: 0.20
    wall_nudge_thresh: 0.20
    nudge_gain: 0.05
    front_corr_thresh: 0.16
    side_corr_thresh: 0.20
    tilt_correction: false
    tilt_thresh: 0.015
    tilt_gain: 1.0
    correction_timeout: 200